// <auto-generated />
using RewardService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace RewardService.Data.Migrations
{
    [DbContext(typeof(RewardDbContext))]
    partial class RewardDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RewardService.Models.PointTransaction", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<Guid>("UserId").HasColumnType("uuid");
                b.Property<int>("Points").HasColumnType("integer");
                b.Property<string>("Type").IsRequired().HasColumnType("text");
                b.Property<string>("Reason").IsRequired().HasColumnType("text");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("IdempotencyKey").HasColumnType("text");
                b.HasKey("Id");
                b.HasIndex("UserId");
                b.HasIndex("IdempotencyKey").IsUnique().HasFilter("\"IdempotencyKey\" IS NOT NULL");
                b.ToTable("Transactions");
            });

            modelBuilder.Entity("RewardService.Models.RewardCriteria", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<string>("Name").IsRequired().HasColumnType("text");
                b.Property<string>("TriggerEvent").IsRequired().HasColumnType("text");
                b.Property<int>("PointsPerUnit").HasColumnType("integer");
                b.Property<decimal?>("MinimumAmount").HasColumnType("numeric");
                b.Property<int?>("BonusPoints").HasColumnType("integer");
                b.Property<bool>("IsActive").HasColumnType("boolean");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.HasKey("Id");
                b.ToTable("Criteria");
            });

            modelBuilder.Entity("RewardService.Models.PointRedemption", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<Guid>("UserId").HasColumnType("uuid");
                b.Property<int>("PointsRedeemed").HasColumnType("integer");
                b.Property<decimal>("MoneyAmount").HasColumnType("numeric");
                b.Property<string>("Status").IsRequired().HasColumnType("text");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("IdempotencyKey").HasColumnType("text");
                b.HasKey("Id");
                b.HasIndex("IdempotencyKey").IsUnique().HasFilter("\"IdempotencyKey\" IS NOT NULL");
                b.ToTable("Redemptions");
            });
#pragma warning restore 612, 618
        }
    }
}
