// <auto-generated />
using WalletService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace WalletService.Data.Migrations
{
    [DbContext(typeof(WalletDbContext))]
    partial class WalletDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WalletService.Models.Wallet", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<Guid>("UserId").HasColumnType("uuid");
                b.Property<decimal>("Balance").HasPrecision(18, 2).HasColumnType("numeric(18,2)");
                b.Property<string>("Currency").IsRequired().HasColumnType("text");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<DateTime>("UpdatedAt").HasColumnType("timestamp with time zone");
                b.HasKey("Id");
                b.HasIndex("UserId").IsUnique();
                b.ToTable("Wallets");
            });

            modelBuilder.Entity("WalletService.Models.WalletTransaction", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<Guid>("WalletId").HasColumnType("uuid");
                b.Property<Guid>("UserId").HasColumnType("uuid");
                b.Property<decimal>("Amount").HasPrecision(18, 2).HasColumnType("numeric(18,2)");
                b.Property<string>("Description").IsRequired().HasColumnType("text");
                b.Property<string>("IdempotencyKey").IsRequired().HasColumnType("text");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.HasKey("Id");
                b.HasIndex("IdempotencyKey").IsUnique();
                b.ToTable("WalletTransactions");
            });
#pragma warning restore 612, 618
        }
    }
}
