<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>NotificationService</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <!-- MassTransit — for consuming events from RabbitMQ -->
    <PackageReference Include="MassTransit" Version="8.2.3" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.2.3" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../shared/Shared.csproj" />
  </ItemGroup>

</Project>
