global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8080']

  - job_name: 'reward-service'
    static_configs:
      - targets: ['reward-service:8080']

  - job_name: 'wallet-service'
    static_configs:
      - targets: ['wallet-service:8080']
