// <auto-generated />
using UserService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace UserService.Data.Migrations
{
    [DbContext(typeof(UserDbContext))]
    partial class UserDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UserService.Models.UserProfile", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<Guid>("AuthUserId").HasColumnType("uuid");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("Email").IsRequired().HasMaxLength(256).HasColumnType("character varying(256)");
                b.Property<string>("FirstName").IsRequired().HasColumnType("text");
                b.Property<string>("LastName").IsRequired().HasColumnType("text");
                b.Property<int>("PointBalance").HasColumnType("integer");
                b.Property<int>("TotalPointsEarned").HasColumnType("integer");
                b.Property<int>("TotalPointsRedeemed").HasColumnType("integer");
                b.Property<DateTime>("UpdatedAt").HasColumnType("timestamp with time zone");
                b.HasKey("Id");
                b.HasIndex("AuthUserId").IsUnique();
                b.HasIndex("Email").IsUnique();
                b.ToTable("UserProfiles");
            });
#pragma warning restore 612, 618
        }
    }
}
